### ISSUE TITLE
NewAppParserFails when reading a PNG from an IPA

### ISSUE THREAD

**Issue by bzon** [phinexdaz/ipapk#3]
Problem:

NewAppParser fails when reading the IPA file 

built from https://github.com/browserstack/xcuitest-sample-browserstack.

Work around:

I had to modify [AndrianBdn/iospng/iospng.go](https://github.com/AndrianBdn/iospng/blob/master/iospng.go) line 104 from `return ErrImageData` to `return nil` to solve the issue.

Does this mean that the browser stack sample app has bad png icon files? How should we handle this? 

I've used this library multiple times on different IPA and it works fine. The sample from browser stack fails to be read. 

You may extract the zip file below to get the build ipa file and test.

[sample_ipa.zip](https://github.com/phinexdaz/ipapk/files/2033664/sample_ipa.zip)

**Comment by kiethen** [comment]
I can't build this project without the Mac, can you give me the IPA file.

2018-05-24 11:03 GMT+08:00 Bryan Sazon <notifications@github.com>:

**Comment by bzon** [comment]
@phinexdaz I've attached it in the issue description.

**Comment by kiethen** [comment]
Sorry, just noticed that.
does this IPA have an icon in the simulator

**Comment by bzon** [comment]
@phinexdaz  it does have an Icon. See the attached app icon. This is the output of running NewAppParser with my fix mentioned in the workaround.

![appicon](https://user-images.githubusercontent.com/19391568/40465051-5161d0f0-5f51-11e8-9354-901f63d161ed.png)

**Comment by bzon** [comment]
@phinexdaz  this is how I fixed it https://github.com/bzon/iospng/commit/8946b47f1625c31425691bd37586fa81d71256ff

**Comment by kiethen** [comment]
yeah, it seems to be working, or remove the function `rawImageFix`.

**Comment by bzon** [comment]
@phinexdaz Can we consider this as the fix? Should we fork that project? I did and is already using my own iospng fork in my ipapk fork.

**Comment by kiethen** [comment]
https://gist.github.com/urielka/3609051#file-ipin-py-L84
`rawImageFix` can return nil if `len(raw) != w*h*4 + h`

**Comment by AndrianBdn** [comment]
@bzon @phinexdaz that was interlaced PNG file; I've updated the code to support it
just returning nil is wrong — colors are not converted

**Comment by bzon** [comment]
Fixed in https://github.com/AndrianBdn/iospng/commit/eb5ebcdb1909fde8a38cac3df227c5717f7577df
